ecs_cluster_name = "norshukri-ecs-cluster-prod"
ecs_service_name = "norshukri-ecs-service-prod"
ecs_task_defn_family = "norshukri-ecs-task-def-prod"
ecs_container_name = "norshukri-container-prod"
ecs_port_name = "norshukri-3000-tcp-prod"